### ISSUE TITLE
Docute 4.0 design

### ISSUE THREAD

**Issue by egoist** [leptosia/docute#112]
- links in sidebar menu will be linked to individual docs page, the links are configurable.

**Comment by imsus** [comment]
Suggestion for UI:

- Stripe: https://stripe.com/docs
- Laravel: https://laravel.com/docs/5.4
- Readme: https://readme.readme.io/docs/introduction

**Comment by egoist** [comment]
@imsus they all look good, maybe I can find a way to make docute support *themes*

**Comment by rigor789** [comment]
Another suggestion for UI:

- Element UI: http://element.eleme.io/#/en-US/component/installation

**Comment by cannap** [comment]
HI
whats about a 3 col layout? this would be cool for api documentations
[Sidebar] [Description] [Code]

**Comment by egoist** [comment]
@cannap have you checked out http://ricostacruz.com/flatdoc/ 👏

**Comment by cannap** [comment]
thank you i searched last night for something but found nothing xD

**Comment by egoist** [comment]
The doc of https://tailwindcss.com/docs/what-is-tailwind/ looks clean

**Comment by egoist** [comment]
update: not going to support pluggable UI,  just seems much more complicated than I thought before

**Comment by egoist** [comment]
I may just follow the design of bootstrap docs 😅 https://getbootstrap.com/docs/4.0/getting-started/introduction/

i.e. 
- Links to doc pages on the left bar
- Main content in the center
- TOC of main content on the right bar

**Comment by egoist** [comment]
I will share development process on our Twitter account, follow https://twitter.com/docute_js if you want to stay up to date 😄

**Comment by egoist** [comment]
Dev branch is now available at https://github.com/egoist/docute/tree/dev

An example is also available at https://example.docute.org

It's still at early stage though 😅

**Comment by ulivz** [comment]
@egoist So about the mobile design, the TOC follows the dropdown style from bootstrap docs, or the old slideUpLeft style?

**Comment by phillbaker** [comment]
@egoist tried out the dev branch, it's looking really good!

One request would be to add a `basePath` parameter in the Docute contructor and then use this on fetch, so that the Docute instance could be used at a subdirectory. E.g.:

```js
# src/index.js
class Docute {
  constructor({
    docs,
    nav,
    defaultFileName = 'README',
    routerMode = 'hash',
    toc,
    site,
    source,
    layouts,
    basePath = '/'
  } = {}) {
    this.config = {
      docs,
      nav,
      defaultFileName,
      routerMode,
      toc,
      site,
      source,
      basePath
    }
    this.layouts = {
      ...defaultLayouts,
      ...layouts
    }
  }
...
// page.vue
const storeMixin = createStoreMixin({
  state: {
    defaultFileName: state => state.config.defaultFileName,
    basePath: state => state.config.basePath,
    site: state => state.config.site
  }
})
...
async fetchAndRender() {
  progress.start()
  const file = this.$route.path === '/' // Homepage
    ? `${this.basePath}${this.defaultFileName}.md`
    // Fetches `/foo.md` for both `/foo` and `/foo/`
    : `${this.$route.path.replace(/\/?$/, '')}.md`
  const [text, MarkdownIt] = await Promise.all([
    fetch(file).then(res => res.text()),
    loadMarkdownParser()
  ])
  progress.done()
  const { attributes, body } = frontMatter(text)
  const html = this.renderToHtml(MarkdownIt, body)
  return {
    ...attributes,
    content: renderAsComponent(html, attributes)
  }
},
```

**Comment by egoist** [comment]
@phillbaker Yeah, that's on our todo list 👍🏻

**Comment by egoist** [comment]
Hey folks, go check out https://vuepress.vuejs.org

I may stop working on v4 because of that 😅

**Comment by egoist** [comment]
@luminarious yeah there're still values for tools like Docute, but Netlify has made the build process so simple that I don't even mind it anymore 😄

**Comment by rikakomoe** [comment]
If we are just trying to implement a sidebar like https://vuepress.vuejs.org/ , here's my idea:

(Based on v3) Add an optional `children` field to `nav`, which is an array of objects. Each object in it has a field `title` and an optional field `children`. Objects with a `children` field indicate they are directories, and the markdown files will be retrieved recursively. In this way could we render a vuepress-like category.

Indeed, the user will have to configure the children manually, which seems not so convenient compared with static, build-required tools like vuepress. But there're still values, for example, we can achieve #105 

But currently I'm confused with why starting a brand new branch instead of basing on v3. I don't see `links in sidebar menu will be linked to individual docs page, the links are configurable.` or "New UI" as sufficient reasons to do so. Is there any other features here?

**Comment by egoist** [comment]
Yeah I'm working on a new version that replicates most features of VuePress's default theme 😂

**Comment by egoist** [comment]
I pushed a new version to master branch, a preview can be found here: https://docute.org

**Comment by egoist** [comment]
The final decision: https://docute.org (I want to make the UI as simple as possible)
