### ISSUE TITLE
Use with mermaid.js

### ISSUE THREAD

**Issue by iamjenmackle** [leptosia/docute#140]
Is there a way to use Docute with Mermaid (UML diagrams)?

**Comment by k1ng440** [comment]
Hello, any progress on this?

i really need this feature

**Comment by vesse** [comment]
We ended up including `mermaid.js` in the index HTML and added this simple plugin (for single graph, but easy enough to render multiple):

```javascript
docute.init({
  ...
  plugins: [
    function(context) {
      context.afterParse(function(html) {
        // https://stackoverflow.com/a/2575797/3349511
        return html.replace(
          /<div class=.mermaid.>([\s\S]*?)<\/div>/g,
          function(match, p1) {
            // https://github.com/knsv/mermaid/issues/506
            var hack = Math.random().toString(36).substring(7).replace(/\d/, "a")
            // https://github.com/knsv/mermaid/blob/a4992963b3873ec7a566ba91b92596d2a360e3b9/src/mermaidAPI.js#L443
            return mermaid.render(hack, p1, function(graph){ });
          }
        );
      });
    }
  ]
});
```

And then in the markdown we have this:

```html
<div class='mermaid'>
sequenceDiagram

Client ->> API: Call API
API ->> Client: Respond
</div>
```

**Comment by k1ng440** [comment]
its doesn't work for me on v4

**Comment by vesse** [comment]
Oh OK, we seem to be using v3.

**Comment by egoist** [comment]
It's available in 4.0.3 now.

Check out the updated docs: https://docute.org/#/guide/writing#using-mermaid

**Comment by k1ng440** [comment]
@egoist thanks but its not clear how to use plugins. can you give an example, please?

**Comment by k1ng440** [comment]
great. thank you

**Comment by egoist** [comment]
I published a standalone module for it: https://cdn.jsdelivr.net/npm/@leptosia/docute-mermaid@1/dist/index.min.js

**Comment by k1ng440** [comment]
@egoist 
graph are all dark
https://codesandbox.io/s/zl5z7o2ml4

https://github.com/knsv/mermaid/issues/736
