### ISSUE TITLE
V4 Responsive design 

### ISSUE THREAD

**Issue by ulivz** [leptosia/docute#153]
Need to enhance the mobile layout for V4.

![image](https://user-images.githubusercontent.com/23133919/38164091-8d65bbce-3531-11e8-895f-f0c16284864b.png)

**Comment by ulivz** [comment]
@egoist  My usual job is mainly to implement the responsive design from designer, I think we need to determine the main breakpoint and layout strategy.

And there is some referenced breakpoint and layout strategy from my past experience:

# 1

Range | Pixel Range | Corresponds to the device | Range Name 
---|---|---|---
`0em -> 35em` | `0 -> 560px` | small mobile | $no-break
`35em -> 53em` | `560px -> 848px` | big mobile | $small-break
`53em -> 71em` | `848px -> 1136px` | tablet | $medium-break
`71em -> 10000em` | `1136px -> 16000px` | desktop  |$large-break

> em is bad, just keep using rem.

# 2

Range | Range name | Corresponds to the device | Layout mode | 
---|---|---|---
`0px -> 829px` | $small | mobile | `percentage` 
`830px -> 1279px` | $medium | tablet stage1 | `percentage` | 
`980px -> 1280px` | $large | tablet stage2 | `pixel-fixed` 
`1280px -> ∞` | $xlarge | desktop | `pixel-fixed`

**Comment by alokpant** [comment]
If any help is needed around this, I offer my services too. 👍
