### ISSUE TITLE
Custom footer documentation

### ISSUE THREAD

**Issue by davidmoshal** [leptosia/docute#198]
Not seeing much info on `registerComponent` as suggested in #26.

Is there an example on how to add a footer?

Documentation often has a copyright notice, so I'm surprised that a footer is not a standard option.

For now am using:
```
    <div style="position: absolute; bottom: 0; right:0; width:80vw; text-align: center">
      &copy;2019 <company name>, Strictly Confidential
    </div>
```

**Comment by egoist** [comment]
I think we can add `footer` and `banner` options, I'll also update the docs for `registerComponent` later.

**Comment by davidmoshal** [comment]
@egoist  thanks

**Comment by egoist** [comment]
Check out https://docute-bg60irzod.now.sh/options#banner--footer.
