### ISSUE TITLE
Feature: custom css for light/dark themes

### ISSUE THREAD

**Issue by jthegedus** [leptosia/docute#206]
Love the new Dark mode #189 support. As an addition, it would be awesome if we could provide two `.css` files each containing separate `:root{}` css  variables for our own custom light/dark theme customization:

```js
theme: {
  "light": "/themes/light.css"
  "dark": "/themes/dark.css"
},
```

If this is already possible via the existing setup and I've misunderstood, I apologize for the noise.

**Comment by egoist** [comment]
Maybe allow the `cssVariables` option to be a function:

```js
new Docute({
  cssVariables(theme) {
     return theme === 'dark' ? {} : {}
  }
})
```

wdyt?

https://docute.org/guide/customization#custom-style

**Comment by jthegedus** [comment]
Would that be used like this?

```js
	return theme === 'dark' ? {
		--success-color: #42b983;	
	} : {
	  --success-color: #008000,
	}
```

Could you elaborate on that a bit more?

**Comment by egoist** [comment]
check out the link in my previous comment

**Comment by jthegedus** [comment]
I did, must have been a cached version of the site as that subheading wasn't there. Opening in a different browser showed the new docs.

Looks like a good solution to me!

**Comment by jthegedus** [comment]
Mate, you work fast! Thanks so much :tada:
